### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by JennieJi** [JennieJi/light-validate-js#6]

**Comment by YashdalfTheGray** [comment]
Do you want just want the types added to this package or is there more to this?

Are you thinking that you want to convert the package to Typescript?

**Comment by YashdalfTheGray** [comment]
I think the first thing I'm going to do is create a `index.d.ts` file for the package and go off the documentation in the README. Let me know if you want me to follow some other thread though 😄

**Comment by JennieJi** [comment]
Hi @YashdalfTheGray , I want to convert the whole project to TypeScript. 

What will happen if only have index ts file? I am a flow user, not so familiar to ts yet. 😅

**Comment by YashdalfTheGray** [comment]
No worries! With an `index.d.ts` file, we can add types to existing Javascript code so your consumers will have types available to them which is pretty much an instant benefit. 

I think we should start there and then eventually convert the whole project to typescript.

**Comment by JennieJi** [comment]
Sounds good to me. 😁Thanks for help!

**Comment by YashdalfTheGray** [comment]
Yep! I should have a PR for you to track in the next couple of days.

Yash Kulshrestha

**Comment by YashdalfTheGray** [comment]
Just been busy with work but I wanted to update you with the direction I'm taking. If you look at [this link][1], they recommend that if the package isn't written in Typescript, then we should publish to [`DefinitelyTyped/DefinitelyTyped`][2] and that's what I was thinking of doing to start. 

Once this project is converted over to typescript, we can then ask the maintainers to deprecate the types from DefinitelyTyped and just vend the types with the project. From a user's perspective, until this project is converted to Typescript, the experience is going to look like

```
npm install --save light-validate-js @types/light-validate-js
```

It is a well established pattern in the Typescript community so there should be nothing to worry about! A lot of big packages like React and Lodash have corresponding `@types/react` and `@types/lodash` packages published to DefinitelyTyped.

[1]: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
[2]: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by JennieJi** [comment]
Hi @YashdalfTheGray ,
 
Thanks for help.  It is a busy week for me, too.

I understand this DefinitelyTyped temporary solution, but this seems not worth your time to do it, as this repo is not widely used yet, and converting to TypeScript is more for preventing contributors to make mistakes.

Since it is a quite small project, it won't take too much time to convert to TS. How about start converting to TS directly? Let me create a branch for that. 😄

**Comment by YashdalfTheGray** [comment]
Perfect, I totally understand. I thought the idea was to provide types to consumers first so I went down the DefinitelyTyped road. I'll start working on my fork of the repo and open a PR as soon as I have some progress!

Thanks for confirming the direction!
